### ISSUE TITLE
Drop Node v10 suport and add v16 as a target version of CI

### ISSUE THREAD

**Issue by koba04** [cybozu/eslint-config#423]
Node v10 has been EOL, so we'll drop Node v10 support.
In addition, I'd like to change the versions for `lint` and `test` GitHub Actions.

## Before (Current)

- lint ... v10
- test ... v10, v12

## After

- lint ... v14
- test ... v12, v14, v16

**Comment by mohzulfikar** [comment]
Hi, I can work on this issue. Can you assign me, please?

**Comment by koba04** [comment]
@mohzulfikar Thank you! Feel free to take this!
