### ISSUE TITLE
[Feature Request] bump typescript-eslint to v6

### ISSUE THREAD

**Issue by tasshi-me** [cybozu/eslint-config#684]
## Why

Originally https://github.com/kintone/js-sdk/issues/2177 by @Lorenzras.

The typescript-eslint v6 has been released, and there are many improvements and breaking changes.
https://typescript-eslint.io/blog/announcing-typescript-eslint-v6/

**Comment by sajikix** [comment]
There are many improvements in v6 and it should be done!

However, as @mshrtsr mentioned, typescript-eslint v6 has major changes to the config and rulesets. The `@typescript-eslint/recommended` ruleset (currently used in this config) also has many rules added, removed, or moved to other rulesets.

## Proposal

So I think it would be better to divide it into 2 steps as follows.

1. update the rules to be the same as they were in v5 as much as possible.
  - Disable all rules newly added to `recommended` in v6.
  - Conversely, rules that were removed from `recommended` in v6 or moved to other rulesets will be activated individually. (except for those that have been completely deleted).

2. having completed 1, discuss the following again
  - Which rules in the newly `recommended` added should be activated?
  - Should we delete rules that have been removed from recommended?
  - New ruleset `stylistic` were created with v6, should they be enabled?

We can do 1 and 2 at the same time, but if users want to update to v6 quickly, I think it is better to do only 1 first and propose/discuss 2 at a later time.

How do you think we should proceed?

**Comment by sajikix** [comment]
fixed by #681 & released as v22 
- https://github.com/cybozu/eslint-config/releases/tag/v22.0.0

**Comment by tasshi-me** [comment]
@sajikix Thank you!!
